import type { RoomDto } from "./room.dto";

/**
 * ⚠️ 1차 구현용 목 데이터 (설계 §11 "데이터")
 *
 * 실제 `GET /rooms`를 붙일 때 이 파일과 `room.api.ts`의 목 로직을 삭제합니다.
 * 컴포넌트는 이 배열을 직접 import 하지 않고 반드시 `fetchRooms`(→ parse → mapper)를
 * 거칩니다 — 그래야 "매퍼만 교체" 약속이 유지됩니다(설계 §6.0c).
 *
 * 썸네일은 `public/mock/rooms/`의 로컬 이미지입니다. `next.config.ts`에
 * `images.remotePatterns`가 없어 외부 URL은 런타임에 막히기 때문입니다(설계 §6.1).
 * 금액은 원 단위입니다(매퍼가 만원으로 변환).
 */

function thumb(): string {
  return "/room/IMG_2593.jpeg";
}

const RAW: ReadonlyArray<Omit<RoomDto, "thumbnailUrl">> = [
  {
    id: "room-01",
    buildingName: "강남 센트럴 푸르지오 시티",
    depositKrw: 10_000_000,
    monthlyRentKrw: 800_000,
    neighborhood: "역삼동",
    transitSummary: "강남역 도보 5분",
    availability: "available",
    availableFrom: "2026-09-01",
  },
  {
    id: "room-02",
    buildingName: "마포 한강 아이파크",
    depositKrw: 5_000_000,
    monthlyRentKrw: 650_000,
    neighborhood: "합정동",
    transitSummary: "합정역 도보 3분",
    availability: "available",
    availableFrom: "2026-09-15",
  },
  {
    id: "room-03",
    buildingName: "관악 브라운스톤 레지던스",
    depositKrw: 3_000_000,
    monthlyRentKrw: 480_000,
    neighborhood: "봉천동",
    transitSummary: "서울대입구역 도보 8분",
    availability: "unavailable",
    availableFrom: null,
  },
  {
    id: "room-04",
    buildingName: "서대문 연희 스퀘어",
    depositKrw: 8_000_000,
    monthlyRentKrw: 720_000,
    neighborhood: "연희동",
    transitSummary: "홍제역 버스 10분",
    availability: "available",
    availableFrom: "2026-10-01",
  },
  {
    id: "room-05",
    buildingName: "성수 서울숲 트리마제",
    depositKrw: 20_000_000,
    monthlyRentKrw: 1_200_000,
    neighborhood: "성수동",
    transitSummary: "뚝섬역 도보 6분",
    availability: "available",
    availableFrom: "2026-09-01",
  },
  {
    id: "room-06",
    buildingName: "종로 익선 한옥 스테이",
    depositKrw: 5_000_000,
    monthlyRentKrw: 900_000,
    neighborhood: "익선동",
    transitSummary: "종로3가역 도보 2분",
    availability: "unavailable",
    availableFrom: "2026-11-01",
  },
  {
    id: "room-07",
    buildingName: "송파 헬리오시티",
    depositKrw: 15_000_000,
    monthlyRentKrw: 950_000,
    neighborhood: "가락동",
    transitSummary: "송파역 도보 4분",
    availability: "available",
    availableFrom: "2026-09-20",
  },
  {
    id: "room-08",
    buildingName: "노원 상계 벨라시티",
    depositKrw: 2_000_000,
    monthlyRentKrw: 420_000,
    neighborhood: "상계동",
    transitSummary: "노원역 도보 7분",
    availability: "available",
    availableFrom: "2026-09-05",
  },
  {
    id: "room-09",
    buildingName: "용산 한강로 센트레빌",
    depositKrw: 12_000_000,
    monthlyRentKrw: 1_050_000,
    neighborhood: "한강로동",
    transitSummary: "용산역 도보 5분",
    availability: "available",
    availableFrom: "2026-10-10",
  },
  {
    id: "room-10",
    buildingName: "동작 흑석 리버파크",
    depositKrw: 7_000_000,
    monthlyRentKrw: 680_000,
    neighborhood: "흑석동",
    transitSummary: "흑석역 도보 3분",
    availability: "unavailable",
    availableFrom: null,
  },
  {
    id: "room-11",
    buildingName: "광진 자양 트라팰리스",
    depositKrw: 9_000_000,
    monthlyRentKrw: 750_000,
    neighborhood: "자양동",
    transitSummary: "건대입구역 도보 6분",
    availability: "available",
    availableFrom: "2026-09-01",
  },
  {
    id: "room-12",
    buildingName: "은평 응암 백련산 SK뷰",
    depositKrw: 4_000_000,
    monthlyRentKrw: 520_000,
    neighborhood: "응암동",
    transitSummary: "새절역 도보 9분",
    availability: "available",
    availableFrom: "2026-09-25",
  },
  {
    id: "room-13",
    buildingName: "강동 고덕 그라시움",
    depositKrw: 11_000_000,
    monthlyRentKrw: 880_000,
    neighborhood: "고덕동",
    transitSummary: "고덕역 도보 4분",
    availability: "available",
    availableFrom: "2026-10-05",
  },
  {
    id: "room-14",
    buildingName: "중랑 면목 두산위브",
    depositKrw: 3_500_000,
    monthlyRentKrw: 450_000,
    neighborhood: "면목동",
    transitSummary: "사가정역 도보 8분",
    availability: "unavailable",
    availableFrom: "2026-11-15",
  },
  {
    id: "room-15",
    buildingName: "양천 목동 하이페리온",
    depositKrw: 18_000_000,
    monthlyRentKrw: 1_100_000,
    neighborhood: "목동",
    transitSummary: "오목교역 도보 5분",
    availability: "available",
    availableFrom: "2026-09-10",
  },
  {
    id: "room-16",
    buildingName: "구로 신도림 디큐브시티",
    depositKrw: 6_000_000,
    monthlyRentKrw: 700_000,
    neighborhood: "신도림동",
    transitSummary: "신도림역 도보 2분",
    availability: "available",
    availableFrom: "2026-09-01",
  },
  {
    id: "room-17",
    buildingName: "성북 길음 뉴타운",
    depositKrw: 5_500_000,
    monthlyRentKrw: 600_000,
    neighborhood: "길음동",
    transitSummary: "길음역 도보 6분",
    availability: "available",
    availableFrom: "2026-10-01",
  },
  {
    id: "room-18",
    buildingName: "영등포 당산 삼성래미안",
    depositKrw: 8_500_000,
    monthlyRentKrw: 780_000,
    neighborhood: "당산동",
    transitSummary: "당산역 도보 4분",
    availability: "unavailable",
    availableFrom: null,
  },
  {
    id: "room-19",
    buildingName: "동대문 답십리 파크자이",
    depositKrw: 7_500_000,
    monthlyRentKrw: 660_000,
    neighborhood: "답십리동",
    transitSummary: "답십리역 도보 5분",
    availability: "available",
    availableFrom: "2026-09-18",
  },
  {
    id: "room-20",
    buildingName: "서초 반포 자이",
    depositKrw: 25_000_000,
    monthlyRentKrw: 1_500_000,
    neighborhood: "반포동",
    transitSummary: "고속터미널역 도보 7분",
    availability: "available",
    availableFrom: "2026-10-20",
  },
  {
    id: "room-21",
    buildingName: "강북 미아 SK북한산시티",
    depositKrw: 2_500_000,
    monthlyRentKrw: 430_000,
    neighborhood: "미아동",
    transitSummary: "미아사거리역 도보 9분",
    availability: "available",
    availableFrom: "2026-09-01",
  },
  {
    id: "room-22",
    buildingName: "금천 독산 롯데캐슬",
    depositKrw: 4_500_000,
    monthlyRentKrw: 540_000,
    neighborhood: "독산동",
    transitSummary: "독산역 도보 6분",
    availability: "unavailable",
    availableFrom: "2026-12-01",
  },
  {
    id: "room-23",
    buildingName: "도봉 창동 주공",
    depositKrw: 2_000_000,
    monthlyRentKrw: 400_000,
    neighborhood: "창동",
    transitSummary: "창동역 도보 5분",
    availability: "available",
    availableFrom: "2026-09-08",
  },
  {
    id: "room-24",
    buildingName: "마포 공덕 래미안",
    depositKrw: 9_500_000,
    monthlyRentKrw: 820_000,
    neighborhood: "공덕동",
    transitSummary: "공덕역 도보 3분",
    availability: "available",
    availableFrom: "2026-10-01",
  },
];

/** 목 매물 DTO 목록 (24건). 로컬 썸네일을 순환 배정합니다. */
export const MOCK_ROOM_DTOS: readonly RoomDto[] = RAW.map((room) => ({
  ...room,
  thumbnailUrl: thumb(),
}));
